sudo: false
language: php

cache:
  directories:
  - $HOME/.composer/cache
  - vendor

matrix:
  fast_finish: true
  include:
  - php: 5.5
    env:
    - EXECUTE_CS_CHECK=true
  - php: 5.6
  - php: 7
  - php: hhvm
  allow_failures:
  - php: 7
  - php: hhvm

before_install:
- openssl aes-256-cbc -K $encrypted_bdfd67bd0d47_key -iv $encrypted_bdfd67bd0d47_iv -in secrets.tar.enc -out .travis/secrets.tar -d
- if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then phpenv config-rm xdebug.ini ||
  return 0 ; fi
- composer self-update

install:
- travis_retry composer install --no-interaction
- composer info -i

script:
- if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then composer test-coverage ; fi
- if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then composer test ; fi
- if [[ $EXECUTE_CS_CHECK == 'true' ]]; then composer cs ; fi

after_script:
- if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then composer coveralls ; fi

after_success:
- tar xvf .travis/secrets.tar -C .travis
- eval "$(ssh-agent -s)" #start the ssh agent
- chmod 600 .travis/build_key.pem
- ssh-add .travis/build_key.pem
- curl -LSs https://box-project.github.io/box2/installer.php | php
- php box.phar build -vv
- mv component-installer.phar component-installer.phar.tmp
- git checkout -b gh-pages origin/gh-pages
- mv component-installer.phar.tmp component-installer.phar
- sha1sum component-installer.phar > component-installer.phar.version
- git add component-installer.phar component-installer.phar.version
- git commit -m 'Rebuilt phar'
- git push origin gh-pages:gh-pages

notifications:
  email: true
